services:
  - type: web
    name: atm-maintenance
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r backend/requirements.txt && cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn atm_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: atm-maintenance.onrender.com,aroundh-ksa.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://aroundh-ksa.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CSRF_TRUSTED_ORIGINS
        value: https://aroundh-ksa.com
      - key: DATABASE_URL
        fromDatabase:
          name: atm-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: yossefhaddad20@gmail.com
      - key: SECRET_KEY
        sync: false

databases:
  - name: atm-db
    databaseName: atm_db_tf06
    user: atm_db_tf06_user
    region: frankfurt
